### ISSUE TITLE
IndexError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by Redfoxbox** [SpockBotMC/SpockBot#226]
I got these error when i try to start example.py, it will connect and event will run but few sec later got error end killed.

> [WARNING]:CHAT: en_US.lang not loaded, cannot translate chat `messages`
Traceback (most recent call last):
  File "example.py", line 58, in <module>
    client.start(SERVER, 25565)
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\helpers\start.py", line 34, in start
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\event.py", line 29, in event_loop
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\event.py", line 36, in run_continuous
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\event.py", line 62, in emit
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\net.py", line 160, in tick
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\select.py", line 70, in poll
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\event.py", line 62, in emit
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\net.py", line 176, in handle_recv
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\net.py", line 114, in read_packet
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\core\event.py", line 62, in emit
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\helpers\world.py", line 101, in handle_map_chunk_bulk
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\tools\smpmap.py", line 247, in unpack_bulk
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\tools\smpmap.py", line 220, in unpack
  File "C:\Users\Redfox\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spockbot-0.2.0-py3.6.egg\spockbot\plugins\tools\smpmap.py", line 172, in unpack
IndexError: cannot fit 'int' into an index-sized integer

**Comment by rom1504** [comment]
are you connecting on a 1.8 server ?

**Comment by Redfoxbox** [comment]
Yes i am, i use "Spigot 1.8.8" server.

**Comment by rom1504** [comment]
Oh actually it looks like master is at 1.9, weird https://github.com/SpockBotMC/SpockBot/commits/master
@Gjum ?

**Comment by nickelpro** [comment]
Looks like 1.9 chunks decoding got merged into master without the rest of the protocol. Either protocol was supposed to be merged in or chunk decoding wasn't lol

SpockBot hasn't been maintained in months though to do @gamingrobot having a real job and me being deployed. Recommend https://github.com/PrismarineJS/mineflayer for all your MC botting needs

**Comment by Redfoxbox** [comment]
Thanks

**Comment by RedNicStone** [comment]
I have the same error on my device,
normal 1.8 bukkit server, but with support for 1.9 to 1.13.
Mineflayer dosen't work for me (becouse of [this](https://github.com/PrismarineJS/mineflayer/issues/873) issue, and i need an highly programmable bot (SpockBotMC fits my needs perfectly).
I'm not that familiar with the MC packages, but i will try my best to help and fix it.
Is [this](https://wiki.vg/index.php?title=Protocol&oldid=7368) the right one for 1.8.8 (Protocol 47)?
