### ISSUE TITLE
convert KeyError: 'blocks'

### ISSUE THREAD

**Issue by lucasfcnunes** [SpockBotMC/SpockBot#230]
I tried to run the example.py but it doesn't work (running in a pipenv):

>**(minecraft-BPM2hraK) (venvs_mgr)>python example.py**
Traceback (most recent call last):
  File "D:\Users\lucas\Desktop\CODING\py\minecraft\SpockBot\examples\basic\example.py", line 18, in <module>
    from example_plugin import ExamplePlugin
  File "D:\Users\lucas\Desktop\CODING\py\minecraft\SpockBot\examples\basic\example_plugin.py", line 17, in <module>
    from spockbot.mcdata import blocks
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\plugins\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\plugins\core\net.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\mcp\mcpacket.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\mcp\extensions.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\mcdata\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\spockbot-0.2.0-py3.7.egg\spockbot\mcdata\blocks.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\minecraft_data-0.4.0-py3.7.egg\minecraft_data\v1_8\__init__.py", line 9, in <module>
  File "D:\Users\lucas\.virtualenvs\minecraft-BPM2hraK\lib\site-packages\minecraft_data-0.4.0-py3.7.egg\minecraft_data\tools.py", line 9, in convert
KeyError: 'blocks'

Can someone help me?

##MORE INFO##
*Running on Windows 10 x64
>**python -V**
Python 3.7.3

>**pip list**
Package        Version
asn1crypto     0.24.0
cffi           1.12.3
cryptography   2.7
entrypoints    0.3
flake8         3.7.7
mccabe         0.6.1
minecraft-data 0.4.0
pip            19.1.1
pycodestyle    2.5.0
pycparser      2.19
pyflakes       2.1.1
setuptools     41.0.1
six            1.12.0
spockbot       0.2.0
wheel          0.33.4

**Comment by Gjum** [comment]
This project never got updated, so it won't work with the latest Minecraft version. See also #227

**Comment by solsahar** [comment]
So I am trying to run the bot on Minecraft 1.8.9 and am still getting the error... Am I supposed to use an earlier version?

**Comment by nickelpro** [comment]
minecraft-data on PyPi is over three years old, I have no idea how it used to work or what was supported for what version back then. I'm starting to ramp back up activity in the MC community again so perhaps I should rev the minecraft-data release, but I removed the API that spockbot uses awhile back so that still won't fix this bug

**Comment by solsahar** [comment]
Ok... I'm sad to hear ;(

Thanks for responding!
