### ISSUE TITLE
KeyError in handle_player_list

### ISSUE THREAD

**Issue by divad** [SpockBotMC/SpockBot#39]
First: thank you for SpockBot - its awesome!

Second, on our server (freebuild.mineactivity.com) sometimes SpockBot crashes like so:

```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    client.start('freebuild.mineactivity.com', 25565)
  File "/usr/lib/python2.7/site-packages/spock/plugins/helpers/start.py", line 37, in start
    self.event.event_loop()
  File "/usr/lib/python2.7/site-packages/spock/plugins/core/event.py", line 22, in event_loop
    self.emit('event_tick')
  File "/usr/lib/python2.7/site-packages/spock/plugins/core/event.py", line 36, in emit
    else copy.deepcopy(data)
  File "/usr/lib/python2.7/site-packages/spock/plugins/core/net.py", line 185, in tick
    self.event.emit(flag)
  File "/usr/lib/python2.7/site-packages/spock/plugins/core/event.py", line 36, in emit
    else copy.deepcopy(data)
  File "/usr/lib/python2.7/site-packages/spock/plugins/core/net.py", line 203, in handleRECV
    self.net.read_packet(data)
  File "/usr/lib/python2.7/site-packages/spock/plugins/core/net.py", line 133, in read_packet
    self.event.emit(packet.str_ident, packet)
  File "/usr/lib/python2.7/site-packages/spock/plugins/core/event.py", line 36, in emit
    else copy.deepcopy(data)
  File "/usr/lib/python2.7/site-packages/spock/plugins/helpers/clientinfo.py", line 161, in handle_player_list
    item = self.uuids[pl['uuid']]
KeyError: 237771049331261779340081663972802975458L
```

It might be because another player left because the only other event happening at that time was a player going offline:

[14:30:12 INFO]: ljhodge lost connection: Disconnected
[14:30:12 INFO]: ItHurtsWhenIP lost connection: Disconnected

(ItHurtsWhenIP is my 'amusing' bot name)

This would seem to be the case since the 128-bit integer 237771049331261779340081663972802975458 matches ljhodge's UUID.

**Comment by divad** [comment]
Right, the problem seems to be that PL_REMOVE_PLAYER is being sent twice every time somebody leaves, and sometimes an odd UUID shows up: 226283696723800921228506126194727547930 (which doesn't match a minecraft account..!). 

On the second PL_REMOVE_PLAYER event it then breaks of course!

**Comment by nickelpro** [comment]
Whoever at Mojang implemented the Player List mechanics needs a swift kick in the nuts. The hacky fix for this is to check if a uuid is present in the player list before removing it and that's what I'm going to do. I have no idea what correct behavior is for this poorly implemented POS.

**Comment by nickelpro** [comment]
Fixed in 71e4f56af57ef47796e8d7f18de0bb9d9b19f578

**Comment by Gjum** [comment]
The same thing happened to me with entities, so watch out for them getting updated/deleted before creation when you implement entity tracking.

**Comment by nickelpro** [comment]
I already implemented entity tracking and _that_ at least seems to follow sane behavior as long as you're spawning all entities correctly: https://github.com/SpockBotMC/SpockBot/blob/master/spock/plugins/helpers/entities.py

You just have to remember that the client player is an entity to, and to track their entity id because from Join Game, because they don't get any other Spawn Entity event.

**Comment by divad** [comment]
Many thanks @nickelpro :)
