### ISSUE TITLE
Crash when trying to place block on invalid y coord

### ISSUE THREAD

**Issue by oey192** [SpockBotMC/SpockBot#43]
When attempting to place a block at a location with a y value that's too large, Spock crashes

e.g. l place 5 254345 29

Entering a y value ≥ 255 causes the crash, but absurdly large x and z values do not seem to break it

Traceback (most recent call last):
  File "run.py", line 19, in <module>
    client.start('obfuscated.url', 12345)
  File "/Library/Python/2.7/site-packages/spock/plugins/helpers/start.py", line 37, in start
    self.event.event_loop()
  File "/Library/Python/2.7/site-packages/spock/plugins/core/event.py", line 22, in event_loop
    self.emit('event_tick')
  File "/Library/Python/2.7/site-packages/spock/plugins/core/event.py", line 36, in emit
    else copy.deepcopy(data)
  File "/Library/Python/2.7/site-packages/spock/plugins/core/net.py", line 184, in tick
    self.event.emit(flag)
  File "/Library/Python/2.7/site-packages/spock/plugins/core/event.py", line 36, in emit
    else copy.deepcopy(data)
  File "/Library/Python/2.7/site-packages/spock/plugins/core/net.py", line 202, in handleRECV
    self.net.read_packet(data)
  File "/Library/Python/2.7/site-packages/spock/plugins/core/net.py", line 130, in read_packet
    self.event.emit(packet.ident, packet)
  File "/Library/Python/2.7/site-packages/spock/plugins/core/event.py", line 36, in emit
    else copy.deepcopy(data)
  File "/Library/Python/2.7/site-packages/spock/plugins/helpers/world.py", line 83, in handle23
    self.world.set_block(p['x'], p['y'], p['z'], data = block_data)
  File "/Library/Python/2.7/site-packages/spock/mcmap/smpmap.py", line 204, in set_block
    chunk = column.chunks[y]
IndexError: list index out of range

**Comment by nickelpro** [comment]
Problem in smpmap.py bounds checking, will fix when I get out of class today

**Comment by nickelpro** [comment]
This bug is kinda odd, but its fixed in: 86ecc4450201f307c96673a64705f95c144fdfa0
